#Nombre del programa: Class
#Número de grupo de Trabajo: 1
#Nombres de los Programadores: Elvis Aguilar Martinez-Joseph Avilez Rodriguez
#Fecha de elaboración del programa: 23/9/24
#Versión del PYTHON: 3.12.3
#Nombre del IDE donde se trabajó el código: Visual Code

#Funciones con retorno de valor

def prueba():
    return "Hola",45,[1,2,3]

c,n,l = prueba()

print(c)
print(n)
print(l)