#Nombre del programa: Class
#Número de grupo de Trabajo: 1
#Nombres de los Programadores: Elvis Aguilar Martinez-Joseph Avilez Rodriguez
#Fecha de elaboración del programa: 23/9/24
#Versión del PYTHON: 3.12.3
#Nombre del IDE donde se trabajó el código: Visual Code

#Funciones sin retorno de valor

def tabla_multiplicar( num):
    for i in range (1,11):
        print( f"{num}*{i}={num*i}")

tabla_multiplicar(5)
print()
tabla_multiplicar(3)